import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactLenis,  useLenis } from '@studio-freight/react-lenis';
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cuberto Clone Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lenis = useLenis(({ scroll }) => {
    // called every scroll
  })
  return (
    <ReactLenis root>
      <html lang="en">
        <body className="text-slate-900">
          <Header />
          {children}
        </body>
      </html>
    </ReactLenis>
    
  );
}
